# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider :docker do |d|
     d.build_dir = "."
     d.build_args = ["-t", "tarsoqueiroz/vagrantdocker:v1.0"]
     d.name = "hashicorp_vagrantdocker"
     d.remains_running = true
     d.has_ssh = true
  end
end
