Vagrant.configure("2") do |config|

  config.vm.define :srv1 do |srv1|
    srv1.vm.box = "generic/ubuntu2204"
    srv1.vm.network "private_network", ip: "192.168.56.3"
  end

  config.vm.define :srv2 do |srv2|
    srv2.vm.box = "generic/ubuntu2204"
    srv2.vm.network "private_network", ip: "192.168.56.4"
  end

end
