apiVersion: apps/v1
kind: Deployment
metadata:
  name: punkdodevops-deploy
spec:
  selector:
    matchLabels:
      app: punkdodevops
  template:
    metadata:
      labels:
        app: punkdodevops
    spec:
      containers:
      - name: punkdodevops
        image: camillamartins/docker-linuxtips:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: punkdodevops-service
spec:
  selector:
    app: punkdodevops
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: punkdodevops-ingress
  labels:
    name: punkdodevops
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: punkdodevops-service
            port: 
              number: 8080
      - pathType: Prefix
        path: "/punk/"
        backend:
          service:
            name: punkdodevops-service
            port: 
              number: 8080
