version: '3'
services:
  vault:
    image: vault
    container_name: vault
    ports:
      - "8200:8200"
    restart: always
    volumes:
      - ./vault.data/logs:/vault/logs
      - ./vault.data/file:/vault/file
      - ./vault-in-docker.hcl:/vault/config/vault.hcl
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.hcl
