kind: ClusterSecretStore
apiVersion: external-secrets.io/v1beta1
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://0a0f122c.nip.io:8200"
      path: "celepar"
      version: "v1"
      auth:
        tokenSecretRef:
          name: "vault-policy-token"
          key: "token"
