kind: ExternalSecret
apiVersion: external-secrets.io/v1beta1
metadata:
  name: external-secret
spec:
  refreshInterval: "30s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: celepar-senha
    creationPolicy: Owner
  data:
  - secretKey: user
    remoteRef:
      key: celepar/senha
      property: user
  - secretKey: password
    remoteRef:
      key: celepar/senha
      property: password
